### ISSUE TITLE
Roldan Uriel Arcadio Avila 1BS cuadro comparativo 

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Roldanuriel#1]
[Roldan Uriel Arcadio Avila 1BS cuadro comparativo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Roldanuriel/files/9638195/Roldan.Uriel.Arcadio.Avila.1BS.cuadro.comparativo.pdf)

**Comment by Jaczibeth** [comment]
Obtuviste un 17% de 20%.
Presentas falta de información, poca presentación, y faltas ortográficas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
